[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Add proper headers configuration
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"

# Configure redirects properly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add basic auth during development if needed
#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200
#  conditions = {Role = ["admin"]}

# Configure Netlify Functions
[functions]
  directory = "netlify/functions"
  included_files = ["dist/**"]

# Configure Edge Functions
[edge_functions]
  directory = "netlify/edge-functions"

